name: Build TPS Bypass (iOS)

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: iOS
          path: tps-bypass-fps-stabilizer

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tps-bypass-fps-stabilizer-ios
          path: ${{ steps.build.outputs.build-output }}
